baseurl = "https://goettinger-klimabuendnis.de"
title = "Göttinger Klimabündnis"
theme = [ "hugo-theme-cleanwhite", "hugo-theme-introduction" ]
languageCode = "de-de"
# Enable comments by entering your Disqus shortname
#disqusShortname = ""
#googleAnalytics = ""
preserveTaxonomyNames = true
hrefTargetBlank = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  # header_image = "img/banner/2021.04-Göttingen_Kreidebilder_2.jpg"
  header_image = "img/banner/2021-02-05_welt_in_der_hand.jpg"
  # posts_image: see content/post/_index.md
  # events_image: see content/event/_index.md
  SEOTitle = "Göttinger Klimabündnis"
  description = "Die Web-Seite der lokalen Vernetzung Göttinger Klimainitiativen"
  keyword = "Göttinger Klimabündnis"
  slogan = "zur Vernetzung der Göttinger Klimainitiativen"
  #sidebar_pow = "img/pow/2021-12-02_Aktion_Greenpeace_Kohleausstieg_bleibt_Handarbeit.jpg" # Bild der Woche: use absolute URL, seeing it's used in both `/` and `/about/`
  #sidebar_pow_description = "Eine Aktion von Greenpeace Göttingen zur Unterstützung der derzeitigen Handarbeiter*innen in Lützerath"
  sidebar_pow = "img/pow/2021-11-30_Klimacamp_zu_Stadt_und_Landkreis.jpg" # Bild der Woche: use absolute URL, seeing it's used in both `/` and `/about/`
  sidebar_pow_description = "Das Göttinger Klimacamp positionierte sich eindeutig zu Stadt und Landreis"
  #sidebar_pow = "img/pow/2021-09-10-fff-mobitag.jpg"
  #sidebar_pow_description = "Banner-Drop auf dem FFF-Mobitag am 10.9."
  #sidebar_pow = "img/pow/2021-08-09-Laschet_vor_Müllberg.png"
  #sidebar_pow_description = "Der Kanzlerkandidat der CDU erklärt die Ergebnisse seiner Klimapolitik (Impressionistische Nachzeichnung einer Fotographie von Rolf Vennenbernd/dpa)"
  #sidebar_pow = "img/pow/2021-06-19-Klimaschutztage_2021_H4F_Aktion.jpg" # Bild der Woche: use absolute URL, seeing it's used in both `/` and `/about/`
  #sidebar_pow_description = "Eine kleine Fitness-Übung beim Stand von Health for Future  zum Markt der Klimaschutztage am 19.6.2021"
  #sidebar_pow = "img/pow/2021-06-19-Klimaschutztage_2021_H4F_Aktion.jpg" # Bild der Woche: use absolute URL, seeing it's used in both `/` and `/about/`
  #sidebar_pow_description = "Akrobatik Aktion von Health for Future zu den Klimaschutztagen am 19.6.2021"

  image_404 = "img/404-bg.jpg"
  title_404 = "Seite nicht erreichbar"

  # leancloud storage for page view counter
  page_view_conter = false 
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = false
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = [" BUND Göttingen"," Craddle to Craddle Göttingen", " Ende-Gelände Göttingen", " EPIZ Göttingen", " Extinction Rebellion Göttingen", " FossilFree Goettingen", " Fridays for Future Göttingen", " GermanZero Göttingen", " Göttingen im Wandel", " Greenpeace Göttingen", " Grüne Hochschulgruppe Göttingen", " Health for Future Göttingen", " JANUN Göttingen", " Klimagruppe Basisdemokratische Linke Göttingen", " Klimaschutz Göttingen e.V", " Kritische Wirtschaftswissenschaften Göttingen", " Lampedusa-Bündnis Göttingen", " Naturfreunde Göttingen", " Parents for Future Göttingen", " Partizipative Initiative für eine lebenswerte Zukunft Göttingen", "Referat für Ökologie und Nachhaltigkeit (AStA der Uni Gö)", " Scientists for Future Göttingen"]
  #sidebar_avatar = "img/goest-logo.png"# use absolute URL, seeing it's used in both `/` and `/about/`
  #sidebar_avatar = "img/picture-of-the-week.png"# use absolute URL, seeing it's used in both `/` and `/about/`
  #sidebar_avatar = "img/pressekonferenz-ratsantraege-20210317.png"# names of pictures need to be lower case, use absolute URL, seeing it's used in both `/` and `/about/`


  featured_tags = true 
  featured_condition_size = 1 

  friends = true
  bookmarks = false
  about_me = true
  recent_posts = true
  recent_events = true
  summarylength = 60
  nexteventdays = 7

  [params.social]
  rss            = true 
  email          = "redaktion@goettinger-klimabuendnis.de"
  about          = "/top/impressum/"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "https://twitter.com/goest14593149"
  #linkedin       = "https://www.linkedin.com/in/yourlinkedinid"
  #stackoverflow  = "https://stackoverflow.com/users/yourstackoverflowid"
  #instagram     = "full profile url in instagram"
  #github         = "https://github.com/yourgithub"
  #wechat         = "your wechat qr code image"
  #medium         = "full profile url in medium"
  #pinterest     = "full profile url in pinterest"
  
  [[params.friend_link]]
  title = "Göttinger Klimabündnis"
  href =  "https://goettinger-klimabuendnis.de"

  #[[params.bookmark_link]]
  #title =  "Pxhere"
  #href = "https://pxhere.com"
  #[[params.bookmark_link]]
  #title = "unsplash"
  #href = "https://unsplash.com"
  
  [[params.additional_menus]]
  title =  "IMPRESSUM"
  href =  "/top/impressum/"
  [[params.additional_menus]]
  title =  "VERANSTALTUNGEN"
  href =  "/event/"
  [[params.additional_menus]]
  title =  "AKTUELL"
  href =  "/post/"
  [[params.additional_menus]]
  title =  "CONTROLLING"
  href =  "/controlling/"
  [[params.additional_menus]]
  title =  "THEMEN"
  href =  "/categories/"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 

[rss]
Limit = 5